### ISSUE TITLE
Input-dependent noise model

### ISSUE THREAD

**Issue by itskalvik** [AaltoML/BayesNewton#24]
Hello,
Thank you for open-sourcing your work! It has been incredibly useful to me ^-^
Also, is there a method to model input-dependent observation noise? (Snelson and Ghahramani, 2006)

**Comment by wil-j-wil** [comment]
Hi. Sorry for the delay in replying. Yes, we call this the `HeteroscedasticNoise` likelihood. See, e.g., `demos/heteroscedastic.py`.
