### ISSUE TITLE
SparseMarkovVariationalGP vs S2CVI

### ISSUE THREAD

**Issue by sethaxen** [AaltoML/BayesNewton#30]
I've been using [`markovflow.SpatioTemporalSparseCVI`](https://secondmind-labs.github.io/markovflow/autoapi/markovflow/models/spatio_temporal_variational/index.html?highlight=spatiotemporalsparsecvi#markovflow.models.spatio_temporal_variational.SpatioTemporalSparseCVI), which implements S2CVI from [this paper](http://proceedings.mlr.press/v130/wilkinson21a/wilkinson21a.pdf), for some modeling, and I'm now experimenting with BayesNewton. Is `SparseMarkovVariationalGP` with a `SpatioTemporalKernel` that has inducing points essentially equivalent to S2CVI?

Also, can the current implementations handle 2 spatial dimensions as well as a temporal dimension?

**Comment by wil-j-wil** [comment]
Hi. Sorry for the delay in replying. Yes these are two different implementations of the same approach. And yes, the implementation can handle multiple spatial dimensions.
