### ISSUE TITLE
air_quality.py demo failing

### ISSUE THREAD

**Issue by Srujan-D** [AaltoML/BayesNewton#35]
Hi, I am trying to run the air_quality demo, and got the data from here https://drive.google.com/file/d/1QcbzFJyAr95zY-B1r-0MkzcX7TReaF6C/view?pli=1.

On running the code as is, I get this error: 
```
Traceback (most recent call last):
  File "/BayesNewton/demos/air_quality.py", line 433, in <module>
    mu = Y_scaler.inverse_transform(mu)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssm/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 1085, in inverse_transform
    X = check_array(
        ^^^^^^^^^^^^
  File "/ssm/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1043, in check_array
    raise ValueError(
ValueError: Found array with dim 3. None expected <= 2.
```
Any help is appreciated, Thanks!

**Comment by jacktang** [comment]
I come to the same issue

**Comment by mathDR** [comment]
what versions of software are you using?

**Comment by Srujan-D** [comment]
bayesnewton          1.3.4
jax                          0.4.13
jaxlib                       0.4.13
numpy                        1.23.5
tensorflow-probability       0.21.0
scikit-learn                 1.4.1.post1
scipy                        1.12.0
pandas                       2.2.1

jax/jaxlib from requirements.txt has version 0.4.14, but i think i was facing some version dependency issues with multiple libraries (can't recall which ones now since this was over a month ago) but got it resolved after switching to 0.4.13.

Thanks!

**Comment by mathDR** [comment]
okay I can submit a PR that implements my "fixes" but what I did was change 
```
print("nlpd: %2.3f" % nlpd)

z_opt = model.kernel.z.value
mu = bayesnewton.utils.transpose(posterior_mean.reshape(-1, N_test, N_test))

mu = Y_scaler.inverse_transform(mu)
Y = Y_scaler.inverse_transform(Y)

save_result = False
```
to
```
print("nlpd: %2.3f" % nlpd)

z_opt = model.kernel.z.value

mu = Y_scaler.inverse_transform(posterior_mean)
mu = bayesnewton.utils.transpose(mu.reshape(-1, N_test, N_test))

Y = Y_scaler.inverse_transform(np.squeeze(Y))

save_result = False
```
which undoes the scaling for the `posterior_mean` and _then_ reshapes it.  Also, we `squeeze Y` to allow the inverse scaling to happen.

**Comment by Srujan-D** [comment]
Thanks a lot, this seems to fix the issue- i don't see the error again. Closing the issue.
