### ISSUE TITLE
How to set initial `Pinf` variable in kernel?

### ISSUE THREAD

**Issue by Fangwq** [AaltoML/BayesNewton#5]
I note that the initial `Pinf` variable for Matern-5/2 kernel  is as follows:
```
        Pinf = np.array([[self.variance,    0.0,   -kappa],
                         [0.0,    kappa, 0.0],
                         [-kappa, 0.0,   25.0*self.variance / self.lengthscale**4.0]])
```
Why it is like that? Any references I should follow up?

PS: by the way, the data `../data/aq_data.csv` is missing.

**Comment by wil-j-wil** [comment]
Perhaps the best reference is Chapter 12 of the textbook 'Applied Stochastic Differential Equations' by Särkkä & Solin. There they explain the approach for the general Matern class.

Thanks for the note about the air quality data. Unfortunately that data set is a bit too big to keep in this repo. Drop me an email if you would like me to send it to you.

**Comment by Fangwq** [comment]
@wil-j-wil, Thanks for your clearance. Here's my email address: shenzhizi124@gmail.com. Thank you again.
