### ISSUE TITLE
question about the equation (64) in `Bayes-Newton` paper

### ISSUE THREAD

**Issue by Fangwq** [AaltoML/BayesNewton#9]
I'm a little confused by the equation (64). It is calculated by equation (63), but where is the other term in equation (64)? such as denominator comes from the covariance of `p(fn|u)`.

**Comment by wil-j-wil** [comment]
Hi, sorry I never got around to this issue. You are correct, the pre-print does have an mistake in it. Equation 63 is actually incorrect, the likelihoods should not be parameterised this way. I will update this in future versions of the paper.

**Comment by wil-j-wil** [comment]
The sparse GP section of the paper has now been corrected in the latest arxiv version: https://arxiv.org/abs/2111.01721
I hope this clears things up.
